### ISSUE TITLE
@2x "Book" icons misaligned?

### ISSUE THREAD

**Issue by kristofferjohansson** [deaghean/omnifocus-perspective-icons#2]
Hi, great job on the icons I really enjoy them!
I don't know if they are meant to, but I noticed that the @2x versions of the "Book" icon are a bit aligned to the right.

**Comment by deaghean** [comment]
Thanks for bringing this to my attention! I'm still not sure why this occurred; a bug in Photoshop Generator perhaps. The icons should be fixed.
