### ISSUE TITLE
Color choice for iOS icons

### ISSUE THREAD

**Issue by sartak** [deaghean/omnifocus-perspective-icons#3]
... would be wonderful :)

**Comment by deaghean** [comment]
Yeah, I've been reticent to add those because I think they'll look funny with teal text next to them. But, I suppose they wouldn't be difficult to add...

I'll see what I can do ;)

**Comment by deaghean** [comment]
Are there particular glyphs you're interested in using? I've [started work on this](https://github.com/deaghean/omnifocus-perspective-icons/blob/dark-palette-support/src/alarm-clock.psd), but it'll take a little time to go through. I'm happy to move certain icons up in the queue.

**Comment by sartak** [comment]
No worries. I appreciate it! 

iPhone$B$+$iAw?.(B

H27/06/11 17:00$B!"(BJosh Hughes <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by deaghean** [comment]
OK, all the icons should have some additional iOS color choices. Enjoy!

**Comment by sartak** [comment]
Thanks very much :)
