### ISSUE TITLE
Colors don't gray the same in the sidebar

### ISSUE THREAD

**Issue by geoelectric** [deaghean/omnifocus-perspective-icons#5]
Using OmniFocus 2.5.3 on El Capitan.

When a perspective isn't selected, the colors are replaced by a grayscale version of the icon. The various default perspectives and the packed-in teal icons all fade to around the same apparent gray, though digital color meter shows that they're actually pretty varied.

The icons you've made are kind of all over the place in terms of how they fade. Orange, Green and Teal are notably lighter than stock when faded, to the point of not looking good, but they do look more or less like each other. Blue and Red fade to a little lighter than stock but not too bad. Graphite and purple fade to around the same as stock. Brown is a little darker than either of those. 

So, summarizing, you get roughly four different grayscale shades out of all the colors:

Very Light:
- Orange
- Green
- Teal

Slightly Light:
- Blue
- Red

Stock:
- Graphite
- Purple

Slightly Dark:
- Brown

Within any group, they fade to the same apparent gray to my eyes. I mention this because maybe there's a commonality in their underlying luminance or something like that going on that would help understand the behavior.

Unfortunately, I've pulled the icons out of OmniFocus before I thought to take a screenshot, but I could probably be convinced to do one if you really need it.

**Comment by geoelectric** [comment]
Did a screenshot quickly anyway. Everything not named after a color is stock, with default teal icons for any custom perspectives. The color ones are using 2x icons. 

I ordered them from apparent lightest to darkest (but didn't check in Color Meter to verify that).

<img width="70" alt="screen shot 2016-05-10 at 8 03 46 pm" src="https://cloud.githubusercontent.com/assets/314134/15168902/8951ba86-16ea-11e6-801d-d25a9c1d0c79.png">

**Comment by deaghean** [comment]
I'm aware of the issue, but I'm not sure there's a good solution. OmniFocus seems to handle custom icons quite differently from the built-in ones.

For example, I created two perspectives. One is setup as a custom icon (which I pulled from the app bundle), and the other is built-in. Same image used, but it renders quite differently:

![custom-vs-builtin](https://cloud.githubusercontent.com/assets/716255/15169270/2509a448-16ff-11e6-8262-1062cdd2e717.png)

**Comment by geoelectric** [comment]
Yeah, I was afraid that might be the case, especially after comparing the two teals before/after the graying out. Theirs is actually somewhat lighter than yours before getting grayed, but darker afterwards. 

I was hoping there was some wrinkle in the color channels leading to this but your experiment does suggest special-casing in the code.
