### ISSUE TITLE
PNG files include gamma value, which was ignored until iOS 11

### ISSUE THREAD

**Issue by papernapkinhead** [deaghean/omnifocus-perspective-icons#6]
Folks running OmniFocus 2.21 TestFlight builds in iOS 11 may have noticed that these icons appear faded, like so: 

<img width="314" alt="example" src="https://user-images.githubusercontent.com/589409/28852981-07571586-76e2-11e7-9684-bcc2da5ee397.png">

iOS 11 appears to respect the 'gamma' value included in these PNG files, which was not shown in iOS 10. Oddly enough, using copy/paste in OmniFocus on Mac strips this metadata, so you may or may not see this symptom, depending on how the perspective icon was added.

The files hosted here contain this metadata. For example, the `trophy/icon-ios-blue@2x.png` shows this gamma value (using the Pillow Python library):

```
>>> img.info['gamma']
0.45455
```

Not sure if your toolchain allows for adjusting this gamma value (or if it's maybe an Adobe bug!). I'd be happy to take a stab at stripping it programmatically if not.

**Comment by deaghean** [comment]
Well, that's a fun one! I ran the icons through ImageOptim, which should remove the gamma value. Mind letting me know if that seems to resolve the issue?

**Comment by papernapkinhead** [comment]
Yep! A small sampling of the icons shows that the gamma value is indeed stripped and syncs as it should to iOS 11 (regardless of how it is set on Mac). Thanks so much!!

**Comment by deaghean** [comment]
Not a problem! Thanks for letting me know!
