### ISSUE TITLE
OmniFocus 3 for Mac icons

### ISSUE THREAD

**Issue by Crocmagnon** [deaghean/omnifocus-perspective-icons#7]
Hi there 👋 
First users have received the preversion of OmniFocus 3 for Mac and the v2 icons don't look very nice with it. When do you think the mac version of the v3 icons will be available ? ☺️

Cheers

**Comment by deaghean** [comment]
Hopefully soon! My goal is to finish the new Mac icons within the next few weeks. I’ve got a bunch done already. Thanks for asking!

**Comment by Crocmagnon** [comment]
Thanks for sharing your timeline with us! 😉
I can't wait 😁 Please comment on this issue when you upload the Mac icons so we can be notified 😇

**Comment by skylarp** [comment]
I’m curious to know how the Mac icons will differ this time around. After a few hours with the macOS beta, I find that the icons I applied during the iOS beta fit in just fine. 🤔

**Comment by deaghean** [comment]
Yeah, the icons I made for iOS fortunately look ok on the Mac. The ones I’m working on now more closely match the built in perspectives however. Here’s an example: https://github.com/deaghean/omnifocus-perspective-icons/blob/version-3/v3/calendar-star/icon-filled-blue%402x.png

**Comment by skylarp** [comment]
Ah, that makes sense. I’m looking forward to seeing them, regardless. 😃

**Comment by deaghean** [comment]
@Crocmagnon @skylarp Tweaks are definitely going to get made here, but [here you go](https://omnifocusicons.josh-hughes.com/)!

**Comment by skylarp** [comment]
Thanks for the heads-up, @deaghean! Congratulations on the initial release—they look amazing to me.

**Comment by Crocmagnon** [comment]
Thanks :)
